=== Sandy4321/statmod.ru/_courses/spec.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" id="courses">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"/>
	<xs:element name="courses">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="course"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="course">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="stringWithLang" minOccurs="0"/>
				<xs:element ref="prof" minOccurs="0"/>
				<xs:element ref="part" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="semester" type="semesterNo"/>
			<xs:attribute name="year" type="yearNo"/>
			<xs:attribute name="class" type="classType"/>
			<xs:attribute name="extras" type="xs:string"/>
			<xs:attribute name="hours" type="xs:unsignedByte"/>
			<xs:attribute name="exam" type="examType"/>
			<xs:attribute name="year_equiv" type="xs:string"/>
			<xs:attribute name="alias" type="courseId"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="prof">
			<xs:complexType>
			 <xs:attribute name="id" type="profId"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="part">
		<xs:complexType>
			<xs:all>
				<xs:element ref="prof"/>
			</xs:all>
			<xs:attribute name="type" type="xs:string"/>
			<xs:attribute name="hours" type="xs:unsignedByte"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="stringWithLang">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute ref="xml:lang"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="courseId">
		<xs:restriction base="xs:string">
			<xs:pattern value="/[a-z]+[_[a-z]]+/"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="profId">
		<xs:restriction base="xs:string">
			<xs:pattern value="/[a-z]{2}_[a-z]{+}/"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="semesterNo">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="5"/>
			<xs:maxInclusive value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="yearNo">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="3"/>
			<xs:maxInclusive value="5"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="classType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="с/к"/>
			<xs:enumeration value="с/с"/>
			<xs:enumeration value="общ."/>
			<xs:enumeration value="ОПД"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="examType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="зачет"/>
			<xs:enumeration value="экз."/>
			<xs:enumeration value="доп."/>
			<xs:enumeration value=""/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Sandy4321/statmod.ru/_courses/sm_spec.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<courses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="spec.xsd">
	<course semester="5" year="3" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="all_teorver_pract">
		<name xml:lang="ru">Теория вероятностей</name>
		<prof id="vv_nekrutin"/>
	</course>
	<course semester="5" year="3" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="sm_prog_c_pract">
		<name xml:lang="ru">Выч. практика</name>
		<prof id="ne_golyandina"/>
	</course>
	<course semester="5" year="3" class="с/к" extras="(1)" hours="2" exam="зачет" year_equiv="0.5" alias="sm_stat_intro">
		<name xml:lang="ru">Введение в обработку данных</name>
		<prof id="ag_bart"/>
	</course>
	<course semester="5" year="3" class="с/с" extras="(1)" hours="2" exam="зачет" year_equiv="0.5" alias="sm_prog_c_lang">
		<name xml:lang="ru">Технология программирования</name>
		<prof id="ne_golyandina"/>
	</course>
	<course semester="6" year="3" class="общ." extras="" hours="2" exam="доп." year_equiv="0.5" alias="all_teorver_pract">
		<name xml:lang="ru">Теория вероятностей</name>
		<prof id="vv_nekrutin"/>
	</course>
	<course semester="6" year="3" class="общ." extras="" exam="доп." year_equiv="" alias="all_teorver_kurs">
		<name xml:lang="ru">Курсовая работа по теор. вер.</name>
		<prof id="vv_nekrutin"/>
	</course>
	<course semester="6" year="3" class="общ." extras="" hours="4" exam="зачет" year_equiv="1" alias="sm_prog_cpp_statmod">
		<name xml:lang="ru">Спец. выч. практикум</name>
		<part type="prog" hours="2">
			<prof id="ne_golyandina"/>
		</part>
		<part type="statmod" hours="2">
			<prof id="vv_nekrutin"/>
		</part>
	</course>
	<course semester="6" year="3" class="с/к" extras="" hours="2" exam="" year_equiv="" alias="sm_statmod">
		<name xml:lang="ru">Статистическое моделирование</name>
		<prof id="vv_nekrutin"/>
	</course>
	<course semester="6" year="3" class="с/с" extras="(1)" hours="2" exam="зачет" year_equiv="0.5" alias="sm_stat_intro_timeseries">
		<name xml:lang="ru">Первичная обработка данных</name>
		<prof id="ag_bart"/>
	</course>
	<course semester="7" year="4" class="общ." extras="" hours="3" exam="экз." year_equiv="0.5" alias="all_statmod">
		<name xml:lang="ru">Мат.модел. и обработка данных</name>
		<part type="lect" hours="2">
			<prof id="sm_ermakov"/>
		</part>
		<part type="pract" hours="1">
			<prof id="ka_timofeev"/>
		</part>
	</course>
	<course semester="7" year="4" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="sm_prog_cpp_advanced">
		<name xml:lang="ru">Спец. выч. практикум</name>
		<prof id="ne_golyandina"/>
	</course>
	<course semester="7" year="4" class="общ." extras="ф." hours="2" exam="зачет" year_equiv="0.5" alias="sm_prog_optimization">
		<name xml:lang="ru">Практикум по совр. прикл. программированию</name>
		<prof id="ne_golyandina"/>
	</course>
	<course semester="7" year="4" class="общ." extras="выб." hours="2" exam="зачет" year_equiv="0.5" alias="all_finance_intro">
		<name xml:lang="ru">Элементы фин.математики</name>
	</course>
	<course semester="7" year="4" class="ОПД" extras="выб." hours="2" exam="зачет" year_equiv="0.5" alias="sm_montecarlo">
		<name xml:lang="ru">Теория метода Монте-Карло</name>
		<prof id="vv_nekrutin"/>
	</course>
	<course semester="7" year="4" class="с/к" extras="(1a)" hours="0" exam="экз." year_equiv="0.5" alias="sm_statmod">
		<name xml:lang="ru">Статистическое моделирование</name>
		<prof id="vv_nekrutin"/>
	</course>
	<course semester="7" year="4" class="с/к" extras="(1b)" hours="2" exam="экз." year_equiv="0.5" alias="sm_stat_mathstat">
		<name xml:lang="ru">Стохастич.методы обработки данных</name>
		<prof id="ag_bart"/>
	</course>
	<course semester="7" year="4" class="с/к" extras="" hours="2" exam="" year_equiv="" alias="sm_stoch_processes">
		<name xml:lang="ru">Основы теории случайных процессов</name>
		<prof id="vv_nekrutin"/>
	</course>
	<course semester="7" year="4" class="с/с" extras="(1)" hours="2" exam="зачет" year_equiv="0.5" alias="sm_exper_design">
		<name xml:lang="ru">Оптимальное планирование эксперимента</name>
		<prof id="vb_melas"/>
	</course>
	<course semester="8" year="4" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="all_stat">
		<name xml:lang="ru">Мат.модел. и обработка данных</name>
		<prof id="ms_ermakov"/>
	</course>
	<course semester="8" year="4" class="общ." extras="ф." hours="2" exam="зачет" year_equiv="0.5" alias="sm_prog_stock_modelling">
		<name xml:lang="ru">Практикум по совр.прикл.программированию</name>
		<prof id="ne_golyandina"/>
	</course>
	<course semester="8" year="4" class="общ." extras="выб." hours="2" exam="зачет" year_equiv="0.5" alias="all_finance_insurance">
		<name xml:lang="ru">Элементы фин.математики</name>
		<prof id="tm_tovstik"/>
	</course>
	<course semester="8" year="4" class="ОПД" extras="выб." hours="5" exam="экз." year_equiv="0.75" alias="all_prog_matlab">
		<name xml:lang="ru">Выч.методы и пакеты в стат.исследованиях</name>
		<part type="lect" hours="3">
			<prof id="an_pepelyshev"/>
		</part>
		<part type="pract" hours="2">
			<prof id="np_alekseeva"/>
		</part>
	</course>
	<course semester="8" year="4" class="с/к" extras="(1a)" hours="2" exam="экз." year_equiv="0.5" alias="sm_markov_processes">
		<name xml:lang="ru">Марковские процессы</name>
		<prof id="ne_golyandina"/>
	</course>
	<course semester="8" year="4" class="с/к" extras="(1b)" hours="0" exam="экз." year_equiv="0.5" alias="sm_stoch_processes">
		<name xml:lang="ru">Основы теории случайных процессов</name>
		<prof id="vv_nekrutin"/>
	</course>
	<course semester="8" year="4" class="с/к" extras="(2)" hours="2" exam="зачет" year_equiv="0.5" alias="sm_stat_analysis">
		<name xml:lang="ru">Многомерная статистика</name>
		<prof id="ag_bart"/>
	</course>
	<course semester="8" year="4" class="с/к" extras="(3)" hours="2" exam="зачет" year_equiv="0.5" alias="sm_marketing_models">
		<name xml:lang="ru">Стох.модели покупат.поведения</name>
		<prof id="vv_nekrutin"/>
	</course>
	<course semester="8" year="4" class="с/с" extras="(1)" hours="2" exam="зачет" year_equiv="0.5" alias="sm_stat_pract">
		<name xml:lang="ru">Анализ  данных на компьютере</name>
		<prof id="ne_golyandina"/>
	</course>
	<course semester="9" year="5" class="с/к" extras="(1)" hours="4" exam="экз." year_equiv="1" alias="sm_stat_stoch_processes">
		<name xml:lang="ru">Статистика случайных процессов</name>
		<prof id="ag_bart"/>
	</course>
	<course semester="9" year="5" class="с/к" extras="(2)" hours="2" exam="экз." year_equiv="0.5" alias="sm_timeseries_ssa">
		<name xml:lang="ru">Главные компоненты временных  рядов</name>
		<prof id="ne_golyandina"/>
	</course>
	<course semester="9" year="5" class="с/к" extras="(3)" hours="2" exam="экз." year_equiv="0.5" alias="sm_queueing_theory">
		<name xml:lang="ru">Системы массового обслуживания</name>
		<prof id="vb_melas"/>
	</course>
	<course semester="9" year="5" class="с/с" extras="(1)" hours="2" exam="зачет" year_equiv="0.5" alias="sm_stat_timeseries">
		<name xml:lang="ru">Стат.анализ временных рядов</name>
		<prof id="ne_golyandina"/>
	</course>
	<course semester="10" year="5" class="с/с" extras="(1)" hours="2" exam="зачет" year_equiv="0.5" alias="sm_stoch_models">
		<name xml:lang="ru">Вероятностные модели</name>
		<prof id="vv_nekrutin"/>
	</course>
</courses>

=== Sandy4321/statmod.ru/_courses/sa_spec.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<courses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="spec.xsd">
	<course semester="5" year="3" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="all_teorver_pract">
		<name xml:lang="ru">Теория вероятностей</name>
		<prof id="vv_nekrutin"/>
	</course>
	<course semester="5" year="3" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="sa_prog_c_pract">
		<name xml:lang="ru">Выч. практика</name>
		<prof id="vb_christinich"/>
	</course>
	<course semester="5" year="3" class="с/к" extras="(1)" hours="2" exam="зачет" year_equiv="0.5" alias="sa_graph_theory">
		<name xml:lang="ru">Структурное представление систем</name>
		<prof id="ya_sushkov"/>
	</course>
	<course semester="5" year="3" class="с/с" extras="(1)" hours="2" exam="зачет" year_equiv="0.5" alias="sa_prog_c_lang">
		<name xml:lang="ru">Алгоритмические языки</name>
		<prof id="vb_christinich"/>
	</course>
	<course semester="6" year="3" class="общ." extras="" hours="2" exam="доп." year_equiv="0.5" alias="all_teorver_pract">
		<name xml:lang="ru">Теория вероятностей</name>
		<prof id="vv_nekrutin"/>
	</course>
	<course semester="6" year="3" class="общ." extras="" exam="доп." year_equiv="" alias="all_teorver_kurs">
		<name xml:lang="ru">Курсовая работа по теор. вер.</name>
		<prof id="vv_nekrutin"/>
	</course>
	<course semester="6" year="3" class="общ." extras="" hours="4" exam="зачет" year_equiv="1" alias="sa_prog_cpp">
		<name xml:lang="ru">Спец. выч. практикум</name>
		<prof id="vb_christinich"/>
	</course>
	<course semester="6" year="3" class="с/к" extras="" hours="2" exam="" year_equiv="" alias="sa_montecarlo">
		<name xml:lang="ru">Численные методы Монте-Карло</name>
		<prof id="ap_sizova"/>
	</course>
	<course semester="6" year="3" class="с/с" extras="(1)" hours="2" exam="зачет" year_equiv="0.5" alias="sa_statmod">
		<name xml:lang="ru">Численное моделирование</name>
		<prof id="ap_sizova"/>
	</course>
	<course semester="7" year="4" class="общ." extras="" hours="3" exam="зачет" year_equiv="0.5" alias="all_statmod">
		<name xml:lang="ru">Мат.модел. и обработка данных</name>
		<part type="lect" hours="2">
			<prof id="sm_ermakov"/>
		</part>
		<part type="pract" hours="1">
			<prof id="ka_timofeev"/>
		</part>
	</course>
	<course semester="7" year="4" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="sa_prog_cpp_advanced">
		<name xml:lang="ru">Спец. выч. практикум</name>
		<prof id="yn_kashtanov"/>
	</course>
	<course semester="7" year="4" class="общ." extras="ф." hours="2" exam="зачет" year_equiv="0.5" alias="sa_prog_threads">
		<name xml:lang="ru">Практикум по совр. прикл. программированию</name>
		<prof id="yn_kashtanov"/>
	</course>
	<course semester="7" year="4" class="общ." extras="выб." hours="2" exam="зачет" year_equiv="0.5" alias="all_finance_intro">
		<name xml:lang="ru">Элементы фин.математики</name>
	</course>
	<course semester="7" year="4" class="ОПД" extras="выб." hours="2" exam="зачет" year_equiv="0.5" alias="sa_finmodel">
		<name xml:lang="ru">Задачи фин.мат. и стат.мод-ие</name>
		<prof id="yn_kashtanov"/>
	</course>
	<course semester="7" year="4" class="с/к" extras="(1)" hours="2" exam="экз." year_equiv="1" alias="sa_montecarlo">
		<name xml:lang="ru">Численные методы Монте-Карло</name>
		<prof id="ap_sizova"/>
	</course>
	<course semester="7" year="4" class="с/к" extras="" hours="2" exam="" year_equiv="" alias="sa_system_model">
		<name xml:lang="ru">Моделирование систем</name>
		<prof id="ya_sushkov"/>
	</course>
	<course semester="7" year="4" class="с/с" extras="(1)" hours="2" exam="зачет" year_equiv="0.5" alias="sa_appl_stat">
		<name xml:lang="ru">Численные методы статистики</name>
		<prof id="ne_golyandina"/>
	</course>
	<course semester="8" year="4" class="общ." extras="" hours="2" exam="зачет" year_equiv="0.5" alias="all_stat">
		<name xml:lang="ru">Методы мат. моделир.</name>
		<prof id="ms_ermakov"/>
	</course>
	<course semester="8" year="4" class="общ." extras="ф." hours="2" exam="зачет" year_equiv="0.5" alias="sa_montecarlo_pract">
		<name xml:lang="ru">Практикум по совр.прикл.программированию</name>
		<prof id="ap_sizova"/>
	</course>
	<course semester="8" year="4" class="общ." extras="выб." hours="2" exam="зачет" year_equiv="0.5" alias="all_finance_insurance">
		<name xml:lang="ru">Элементы фин.математики</name>
		<prof id="tm_tovstik"/>
	</course>
	<course semester="8" year="4" class="ОПД" extras="выб." hours="5" exam="экз." year_equiv="0.75" alias="all_prog_matlab">
		<name xml:lang="ru">Выч.методы и пакеты в стат.исследованиях</name>
		<part type="lect" hours="3">
			<prof id="an_pepelyshev"/>
		</part>
		<part type="pract" hours="2">
			<prof id="np_alekseeva"/>
		</part>
	</course>
	<course semester="8" year="4" class="с/к" extras="(1)" hours="2" exam="экз." year_equiv="1" alias="sa_system_model">
		<name xml:lang="ru">Моделирование систем</name>
		<prof id="ya_sushkov"/>
	</course>
	<course semester="8" year="4" class="с/к" extras="(2)" hours="2" exam="зачет" year_equiv="0.5" alias="sa_stat_pract">
		<name xml:lang="ru">Анализ данных и стат.пакеты</name>
		<prof id="ne_golyandina"/>
	</course>
	<course semester="8" year="4" class="с/к" extras="(3)" hours="2" exam="зачет" year_equiv="0.5" alias="sa_parallel_comp">
		<name xml:lang="ru">Введение в парал.вычисления</name>
		<prof id="sm_ermakov"/>
	</course>
	<course semester="8" year="4" class="с/с" extras="(1)" hours="2" exam="зачет" year_equiv="0.5" alias="sa_system_model_pract">
		<name xml:lang="ru">Моделирование систем</name>
		<prof id="ya_sushkov"/>
	</course>
	<course semester="9" year="5" class="с/к" extras="(1)" hours="4" exam="экз." year_equiv="1" alias="sa_automaton_model">
		<name xml:lang="ru">Автоматное моделирование</name>
		<prof id="ay_ponomareva"/>
	</course>
	<course semester="9" year="5" class="с/к" extras="(2)" hours="2" exam="экз." year_equiv="0.5" alias="sa_simul_stoch_proc">
		<name xml:lang="ru">Моделирование случайных процессов</name>
		<prof id="tm_tovstik"/>
	</course>
	<course semester="9" year="5" class="с/к" extras="(3)" hours="2" exam="экз." year_equiv="0.5" alias="sa_decision_make">
		<name xml:lang="ru">Принятие решений</name>
		<prof id="ya_sushkov"/>
	</course>
	<course semester="9" year="5" class="с/с" extras="(1)" hours="2" exam="зачет" year_equiv="0.5" alias="sa_simul_stoch_proc_pract">
		<name xml:lang="ru">Моделирование случайных процессов</name>
		<prof id="tm_tovstik"/>
	</course>
	<course semester="10" year="5" class="с/с" extras="(1)" hours="2" exam="зачет" year_equiv="0.5" alias="sa_decision_make_pract">
		<name xml:lang="ru">Постановка задач и принятие решений</name>
		<prof id="ya_sushkov"/>
	</course>
</courses>
