=== Sandy4321/statmod.ru/_termpapers/termpapers.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema generated by XMLSpy v2005 rel. 3 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="biblitem">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="author" type="xs:string" minOccurs="0"/>
				<xs:element name="title" type="xs:string" minOccurs="0"/>
				<xs:element name="publisher" type="xs:string" minOccurs="0"/>
				<xs:element name="pages" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="paper">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="title" type="xs:string"/>
				<xs:element ref="biblitem" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="prof">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="paper" maxOccurs="unbounded"/>
				<xs:element name="comment" type="xs:string" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="comments">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="publisher"/>
	<xs:element name="termpapers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="prof" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="year" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:enumeration value="2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="title" type="xs:string"/>
</xs:schema>

=== Sandy4321/statmod.ru/_termpapers/termpapers2.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<?xml-stylesheet type="text/xsl" href="termpapers.xsl"?>
<termpapers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" year="2" xsi:noNamespaceSchemaLocation="termpapers.xsd">
	<prof id="sm_ermakov">
		<location>к. 4503</location>
		<paper>
			<title>Равномерно распределенные последовательности. (Небольшие теоретические задачи и вычислительные примеры. Знания теории вероятностей не требуется!)
			</title>
		</paper>
		<paper>
			<title>Эксперименты по вычислению интегралов по многомерному гиперкубу.
			</title>
		</paper>
			<paper>
			<title>Генетические алгоритмы и метод Метрополиса.
			</title>
		</paper>
		</prof>
<prof id="vv_nekrutkin" comments="yes">
		<location>к. 4502</location>
		<paper>
			<title>Дискретная теория вероятностей.</title>
			<biblitem>
				<author>А.Н. Ширяев</author>
				<title>Вероятность</title>
				<publisher>М., Наука, 1989.</publisher>
				<pages>1-я глава</pages>
			</biblitem>
		</paper>
		<paper>
			<title>Испытания Бернулли на отрезке [0,1].</title>
			<biblitem>
				<author>М.Кац</author>
				<title>Статистическая независимость в теории вероятностей, анализе и теории чисел</title>
				<publisher>М., 1983</publisher>
			</biblitem>
		</paper>
		<paper>
			<title>Теория меры и теория вероятностей.</title>
			<biblitem>
				<author>К. Партасарати</author>
				<title> Введение в теорию вероятностей и теорию меры</title>
				<publisher>Москва, Мир, 1983.</publisher>
			</biblitem>
		</paper>
		<paper>
			<title>Краткий курс теории вероятностей.</title>
			<biblitem>
				<author>Н.Чернова</author>
				<title> Теория верояностей. Учебное пособие.</title>
				<publisher>Новосибирск, 2009.</publisher>
			</biblitem>
		</paper><comment>Все темы являются учебными, необходимо прочитать
соответствующий материал и решить задачи.</comment>
	</prof>
	<prof id="ai_korobeynikov">
		<location>к.4502</location>
		<paper>
			<title>Метод Метрополиса и моделирование простейших графических моделей: модель Изинга, модели перколяции.</title>
		</paper>
			<comment>Найдется тема и для тех, кто уже умеет программировать на хорошем уровне.
		</comment>
	</prof>
	
	<prof id="ne_golyandina">
		<location>к. 4502</location>
		<paper>
			<title>Анализ главных компонент как метод "разглядывания" и сжатия многомерных данных.
			</title>
		</paper>
		<paper>
			<title>Марковские цепи и моделирование случайных сценариев.
			</title>
		</paper>
		<paper>
			<title>Некоторые парадоксы теории вероятностей.
			</title>
		</paper>
		<comment> Первая тема является входом в тематику, посвященную применению метода "Гусеница"-SSA к анализу и прогнозу
		временных рядов (см. http://gistatgroup.com/gus/).
		</comment>
	</prof>
	<prof id="np_alekseeva" comments="yes">
		<location>к. 4504</location>
		<paper>
			<title>Математический аспект закона Харди-Вайнберга (генетика).
			</title>
		</paper>
		<paper>
			<title>Блок-схемы и их применение в статистике.
			</title>
		</paper>
		<paper>
			<title>Полиномы Жегалкина и их приложения в многофакторных задачах.
			</title>
		</paper>
		</prof>
	<prof id="vb_melas" comments="yes">
		<location>к. 4395</location>
		<paper>
		
			<title>Решение реальных задач с помощью исследования неявных функций.</title>
						<biblitem>
				<author>В.Б.Мелас</author>
				<title>По запросу от руководителя</title>
				<publisher></publisher>
			</biblitem>
		</paper>
		<comment>Неявные функции возникают при решении многих реальных задач связанных с нахождением оптимальных параметров, 
например, при выборе наиболее выгодной покупки. Планируется решение ряда примеров с помощью рекуррентных формул, 
введенных в работах научного руководителя.
Русскоязычные материалы по теме доступны у научного руководителя по эл. почте.</comment>
		<paper>
			<title>Стратегии успеха. Как получить максимальный бонус?</title>
		</paper>
		<comment>В реальности часто приходится принимать решения в условиях неопределенности. 
		Рассмотрим такую модельную задачу. В корзине находится несколько призов. Размер призов неизвестен, но известно их общее число. 
		Разрешается сделать несколько попыток. Каждый раз вынимается записка с размером бонуса. 
		Можно принять бонус и на этом игра заканчивается. Можно отказаться от бонуса, и при этом записка не возвращается в корзину, 
		а данный бонус больше недоступен. 
		Требуется предложить несколько альтернативных стратегий и сравнить их между собой с помощью компьютерного эксперимента.</comment>
    	</prof>
	
		<prof id="pv_shpilev">
		<location>к. 4395</location>
		<paper>
			<title>Задачи по планированию экспериментов. Исследование простейших моделей 
(число неизвестных параметров 1,2). Нахождение планов в явном виде 
для различных критериев оптимальности. 
			</title>
		</paper>
			<paper>
			<title>Задачи по построению регрессии. Нахождение оценок параметров. 
Вырожденные случаи, обобщенно-обратные матрицы. 
			</title>
		</paper>
	</prof>

<!--
	<prof id="vn_solntsev">
		<location>к. 4504</location>
		<paper>
			<title>Геометрия многомерного пространства (углы между подпространствами).
			</title>
		</paper>
	</prof>
	-->

	<prof id="tm_tovstik">
		<location>к. 4398</location>
		<paper>
			<title>Некоторые задачи, связанные с бросанием случайных точек в геометрические фигуры.
			</title>
		<biblitem>
				<author>Соболь И.М. </author>
				<title>Численные методы Монте-Карло</title>
				<publisher>М., Наука, 1973.</publisher>
			</biblitem>
		</paper>
		<paper>
			<title>Расчет некоторых задач в системе массового обслуживания.</title>
		<biblitem>
				<author>Хинчин А.Я. </author>
				<title>Математические методы теории массового обслуживания</title>
				<publisher>1955.</publisher>
			</biblitem>
		</paper>
	</prof>
	<prof id="nm_moskaleva" comments="yes">
		<location>к. 4398, nimos07@rambler.ru, тел. 534-71-84, 8-905-265-87-24
</location>
		<paper>
			<title>Моделирование цепей Маркова для решения задач линейной алгебры.</title>
					</paper>
		<paper>
			<title>Схема Неймана-Улама применительно к решению линейных интегральных уравнений.</title>
		<biblitem>
				<author>Соболь И.М. </author>
				<title>Численные методы Монте-Карло</title>
				<publisher>М., Наука, 1973.</publisher>
			</biblitem>
			<biblitem>
				<author> Ермаков С.М.</author>
				<title>Метод Монте-Карло и смежные вопросы.</title>
				<publisher>М., Наука, 1975.</publisher>
			</biblitem>
</paper>
	</prof>
  <!--
	<prof id="ay_ponomareva">
		<location>к. 3316</location>
		<paper>
			<title>Оптимальное взаимодействие моделей дискретных процессов и систем с «нечеткой» (fuzzy) средой.</title>
		</paper>
		<paper>
			<title>Оптимальное управление «нечеткой» дискретной системой (процессом) в «нечетких» условиях.</title>
		</paper>
		<paper>
			<title>Нечеткие автоматные модели.</title>
		</paper>
	</prof>
	-->
		<prof id="nk_krivulin">
		<location>к. 4395</location>
		<paper>
			<title>Тропические вейвлет-преобразования в алгоритмах кодирования изображений.
			</title>
		</paper>
		<paper>
			<title>Многомерные задачи размещения Ролза.
			</title>
		</paper>
		<paper>
			<title>Эволюционные уравнения Беллмана: примеры и решение.
			</title>
		</paper>
		<paper>
			<title>Методы идемпотентной алгебры в задачах сетевого планирования.</title>
		</paper>
		<paper>
			<title>Собственные числа и собственные векторы в тропической математике.
			</title>
				<biblitem>
				<author>Маслов В. П., Колокольцов В. Н.</author>
				<title>Идемпотентный анализ и его применение в оптимальном управлении.</title>
				<publisher>М.: Физматлит, 1994.</publisher>
			</biblitem>
			<biblitem>
				<author>Кривулин Н. К.</author>
				<title>Методы идемпотентной алгебры в задачах моделирования и анализа сложных систем.</title>
				<publisher>СПб.: Изд-во С.-Петерб. ун-та, 2009.</publisher>
			</biblitem>
				</paper>
	</prof>
	<prof id="ms_ermakov">
		<location>тел. +7 911 1322167, к.4503</location>
		<paper>
			<title>Прочитать  первые  4 главы учебника Феллера "Теория вероятностей" и решить задачи из 4 главы  6,8,16,17,19,22.</title>
		</paper>
		<paper>
			<title>Прочитать главы 1-4 из учебника Кремера "Теория вероятностей и математическая статистика" и решить задачи гл 3 - 45, 54, 57, гл 4 - 15, 20, 22, 24.
</title>
		</paper>
		<paper>
			<title>Анализ качественных признаков статистическими методами (ранговые критерии при частичном совпадении наблюдений). 
Тема предполагает первичное знакомство с простейшими разделами статистики и два альтернативных метода исследования: простейшим вероятностным моделированием 
или решением не очень сложных комбинаторных задач. Ожидается некоторый творческий взгляд на эту задачу, конечно, совместно со мной.</title>
			</paper>
				<paper>
			<title>Решить задачи из учебника Карлина "Теория случайных процессов" гл 2 (все).</title>
			</paper>
					<paper>
			<title>Методы первичной обработки статистических данных. Ожидается в процессе выполнения работы знакомство с простейшими задачами 
статистики на основе одного из учебников по статистике американской бизнес школы и начальное знакомство с одним из пакетов статистических программ, в частности R.</title>
			</paper>
					<paper>
			<title>Исследование качества непараметрических критериев при разных альтернативах.</title>
			</paper>
	</prof>
	
	</termpapers>
