=== Sandy4321/statmod.ru/_staff/staff.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema generated by XMLSpy v2005 rel. 3 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="about">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="br"/>
				<xs:element ref="p"/>
				<xs:element ref="ol"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="br" type="xs:string"/>
	<xs:element name="duty">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="shortname"/>
			</xs:sequence>
			<xs:attribute name="academic_rank" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="assoc_prof"/>
						<xs:enumeration value="prof"/>
						<xs:enumeration value="senior_rf"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="extlink">
		<xs:complexType mixed="true">
			<xs:attribute name="href" type="xs:string" use="required"/>
			<xs:attribute name="target" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="field" type="xs:string"/>
	<xs:element name="fn" type="xs:string"/>
	<xs:element name="i">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="spec"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="b">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="spec"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="spec">
		<xs:complexType>
			<xs:attribute name="code" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="image">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="w" type="xs:short" use="required"/>
			<xs:attribute name="h" type="xs:short" use="required"/>
			<xs:attribute name="tw" type="xs:short" use="required"/>
			<xs:attribute name="th" type="xs:short" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="li" type="xs:string"/>
	<xs:element name="ln" type="xs:string"/>
	<xs:element name="mn" type="xs:string"/>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="ol">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="li" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="p">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="i"/>
				<xs:element ref="span"/>
				<xs:element ref="spec"/>
				<xs:element ref="b"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="person">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fn"/>
				<xs:element ref="mn"/>
				<xs:element ref="ln"/>
				<xs:element ref="duty" minOccurs="0"/>
				<xs:element ref="image" minOccurs="0"/>
				<xs:element ref="field"/>
				<xs:element ref="about"/>
				<xs:element ref="extlink" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="degree" type="xs:string" use="required"/>
			<xs:attribute name="academic_rank" type="xs:string" use="required"/>
			<xs:attribute name="image" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="shortname" type="xs:string"/>
	<xs:element name="span">
		<xs:complexType mixed="true">
			<xs:attribute name="class" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="staff">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="person" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Sandy4321/statmod.ru/_staff/prof.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<!DOCTYPE staff SYSTEM "/htmlentities.dtd">
<staff xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="staff.xsd">
	<person id="sm_ermakov" degree="phd_d" academic_rank="prof">
		<fn>Сергей</fn>
		<mn>Михайлович</mn>
		<ln>Ермаков</ln>
		<duty academic_rank="prof">
			<name>Заведующий кафедрой</name>
			<shortname>Зав. кафедрой</shortname>
		</duty>
		<image name="ermakov.gif" w="178" h="204" tw="89" th="103"/>
		<field>
			<!-- Область научных интересов -->

очень обширна, включая метод Монте-Карло (вероятностное решение нелинейных уравнений, 
вычисление методом Монте-Карло интегралов в смысле главного значения, исследование асинхронных
стохастических алгоритмов, исследование стохастической устойчивости метода Монте-Карло и многое другое),
теорию планирования регрессионных и имитационных экспериментов. <!--Подробнее можно прочитать в <a href="http://www.vega.math.spbu.ru/jubiley/ermakov/ermakov.htm">статье, посвященной юбилею С.М.Ермакова</a>.-->
		</field>
		<about/>
		<extlink href="/vega/ermakov/ermakov.htm">Статья в юбилейном сборнике кафедры и лаборатории </extlink>
	</person>
	<person id="ap_sizova" degree="phd" academic_rank="assoc_prof" image="sizova">
		<fn>Алла</fn>
		<mn>Филипповна</mn>
		<ln>Сизова</ln>
		<duty academic_rank="assoc_prof">
			<!-- academic_rank:  (доцент/профессор/ст.научн. сотрудник) в должности ->  (accos_prof/prof/senior_rf)-->
			<name>зам.декана</name>
			<shortname>Зам. декана</shortname>
		</duty>
		<image name="sizova.gif" w="178" h="216" tw="84" th="103"/>
		<field>
		Решение задач математической и статистической физики методами Монте-Карло.
					<!-- Область научных интересов -->
		</field>
		<about>
			<!-- Текст -->
		</about>
	</person>
	<person id="ya_sushkov" degree="phd_d" academic_rank="prof" image="sushkov">
		<fn>Юрий</fn>
		<mn>Акимович</mn>
		<ln>Сушков</ln>
		<duty academic_rank="prof">
			<name>Руководитель специализации САПР</name>
			<shortname/>
		</duty>
		<image name="sushkov.gif" w="178" h="213" tw="86" th="103"/>
		<field>
Дискретная математическая теория графов и гиперграфов, методы дискретной и стохастической оптимизации, структурно управляемые системы, моделирование систем. Международный арбитр и международный мастер по шахматным композициям.
		</field>
		<about>
			<p>С появлением персональных компьютеров оказалось возможным
построение психологически совместимых с человеком (лицом, принимающим
решение) диалоговых систем, позволяющих организовать принятие
решения на множестве альтернатив в процессе общения человека с
компьютером. При этом можно было работать с несколькими критериями, с
экспертными оценками, нечетко определенными критериями. </p>
			<p>В последнее десятилетие было построено несколько подобных
программных комплексов, причем создавались они, как правило, в рамках
курсовых и дипломных работ студентов. Разработанные комплексы
неоднократно использовались для принятия решения в различных
организациях. В частности, была решена задача по выбору фундамента при
строительстве порта в Ленинградской области. </p>
			<p>В области дискретной математики была разработана оригинальная
теория связности
гиперграфов, на основе которой были разработаны методы синтеза систем
со структурным управлением, имеющих важное практическое применение. </p>
			<p>Очень важно, что в выполнении указанных работ принимали и
сейчас принимают самое активное участие студенты и аспиранты,
обучающиеся на нашей кафедре.</p>
		</about>
		<extlink href="/vega/syschkov/syschkov.htm">Статья в юбилейном сборнике кафедры и лаборатории </extlink>
	</person>
	<person id="mk_chirkov" degree="phd_d" academic_rank="prof" image="chirk">
		<fn>Михаил</fn>
		<mn>Константинович</mn>
		<ln>Чирков</ln>
		<duty academic_rank="prof">
			<name>Руководитель специализации ММ</name>
			<shortname/>
		</duty>
		<image name="chirk.gif" w="178" h="213" tw="86" th="103"/>
		<field>дискретная математика, математическое моделирование дискретных процессов и систем, теория и приложения обобщенных автоматных моделей различного типа и сетей Петри, нечеткие множества и моделирование дискретных систем и процессов принятия решений в нечетких условиях, нечеткая логика и системы нечеткого вывода</field>
		<about>
			<p>Возглавляя в течение более 20-ти лет Научно-исследовательский институт математики и механики им. акад. В.И.Смирнова, Чирков Михаил Константинович с 2002 г. перешел на преподавательскую работу профессором на кафедру статистического моделирования, организовав новую специализацию «Математическое моделирование». Является председателем редакционно-издательского Совета математико-механического факультета. В 1996 г. избран членом-корреспондентом Российской Академии естественных наук (РАЕН).</p>
			<p>Чирков М.К. &ndash; один из ведущих специалистов в мире в области теории математических моделей конечно-автоматного типа. Результаты М.К.Чиркова нашли практическое применение при создании ряда специализированных вычислительных и управляющих устройств. Всего он опубликовал более 130 научных работ, включая 5 монографий, учебное пособие, более 120 научных статей, и получил 6 авторских свидетельств. Семь его аспирантов успешно защитили кандидатские диссертации и работают в России, Венгрии, Вьетнаме, Сирии, Чехии, один из его учеников защитил докторскую диссертацию.</p>
		</about>
		<extlink href="/vega/tchirkov/tchirkov.htm">Статья в юбилейном сборнике кафедры и лаборатории </extlink>
	</person>
	<person id="vb_melas" degree="phd_d" academic_rank="prof" image="melas">
		<fn>Вячеслав</fn>
		<mn>Борисович</mn>
		<ln>Мелас</ln>
		<duty academic_rank="prof">
			<name/>
			<shortname/>
		</duty>
		<image name="melas.gif" w="178" h="208" tw="88" th="103"/>
		<field>
прикладная статистика
(планирование
эксперимента, регрессионный анализ и стохастическое моделирование).
		</field>
		<about>
			<p>"В математике я стараюсь быть поэтом, композитором и мастером
			спорта одновременно, а иногда и немножко философом".</p>
			<p>В.Б.Мелас &ndash; автор четырех монографий и более 110 статей. Под его руководством успешно защитили кандидатские диссертации Т.В.Фомина (1998), 
			Л.А.Крылова (2000), А.Н. Пепелышев (2002). Является членом редколлегии журнала Journal of Statistical Planning and Inference (с 1996). 
			Один из главных организаторов серии международных конференций в Санкт-Петербурге (St.Petersburg Workshops on Simulation).</p>
		</about>
		<extlink href="/vega/melas/melas.htm">Статья в юбилейном сборнике кафедры и лаборатории </extlink>
	</person>
	<person id="ms_ermakov" degree="phd_d" academic_rank="prof" image="ermakov_m">
		<fn>Михаил</fn>
		<mn>Сергеевич</mn>
		<ln>Ермаков</ln>
		<duty academic_rank="prof">
			<name/>
			<shortname/>
		</duty>
		<image name="ermakovm.gif" w="178" h="218" tw="84" th="103"/>
		<field>
математическая статистика: непараметрические методы статистики, статистическое моделирование в математической статистике, некорректные задачи.
		</field>
		<about>
			<p>"Родился в 1952 году. В 1976 году окончил математико-механический факультет Ленинградского Университета. После этого до последнего времени больше 6 лет на одном месте не сидел (Ленинградское отделение математического института им.Стеклова, Институт Аналитического приборостроения АН СССР, НИИ Физики Физфака, Институт проблем машиноведения РАН…). Занимался как прикладными так и теоретическими задачами. Имею довольно широкую область исследований в указанных выше наиболее интенсивно развивающихся областях математической статистики, связанных со статистическими выводами о значениях функций заданных со случайной ошибкой и вероятностным моделированием в математической статистике."</p>
		</about>
	</person>
	<person id="vv_nekrutin" degree="phd" academic_rank="assoc_prof" image="nekr">
		<fn>Владимир</fn>
		<mn>Викторович</mn>
		<ln>Некруткин</ln>
		<duty academic_rank="assoc_prof">
			<name>Руководитель специализации СМ</name>
			<shortname/>
		</duty>
		<image name="nekr.gif" w="178" h="211" tw="86" th="103"/>
		<field>
теоретические аспекты прикладной теории вероятностей (статистическое моделирование и метод Монте-Карло,
случайный поиск, анализ данных и модели математической статистики, анализ временных рядов и стохастические процессы, вероятностные модели
эконометрики). 
		</field>
		<about>
			<br/>
			<p>
				<i>Из ответа на вопрос студентов 5-го курса &laquo;Что бы Вы пожелали студентам&raquo;:</i>
			</p>
			<p>&laquo;Есть некоторое, я даже не знаю, правило&nbsp;–&nbsp;не правило:</p>
			<ol>
				<li>надо стремиться делать только то, что тебе нравится</li>
				<li>все, что ты делаешь, надо стараться делать хорошо, вне зависимости от того, нравится тебе или не нравится.</li>
			</ol>
			<p>А по совокупности эти вещи означают вот что: не всегда возможно делать то, что тебе нравится (хоть и надо стремиться). И <span class="interesting">если ты попадаешь в ситуацию, которая тебе не нравится, то ее надо отработать и с очень большой вероятностью она тебе начнет нравиться</span>.
</p>
			<p>Это - общее правило, и для меня тоже. И к вам оно сильно, вообще говоря, относится, потому что, так или иначе, но вы попали в ту ситуацию, в которую попали: ошиблись вы или не ошиблись (&laquo;не тот самолет&raquo;, &laquo;не тот город&raquo;, &laquo;не в ту дверь зашел&raquo;), по каким причинам &ndash; это неважно. 
</p>
			<p>Это мое мнение и является объяснением моего отношения к вам.&raquo;</p>
		</about>
	</person>
	<person id="ne_golyandina" degree="phd" academic_rank="assoc_prof" image="neg">
		<fn>Нина</fn>
		<mn>Эдуардовна</mn>
		<ln>Голяндина</ln>
		<duty academic_rank="assoc_prof">
			<name>ученый секретарь кафедры</name>
			<shortname/>
		</duty>
		<image name="neg.gif" w="178" h="217" tw="84" th="103"/>
		<field>
 прикладная статистика
(анализ временных рядов, построение моделей реальных данных,
статистическая обработка данных), решение дифференциальных и
интегральных уравнений методом Монте Карло.
