=== Sandy4321/statmod.ru/_annot/annot.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema generated by XMLSpy v2005 rel. 3 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"/>
	<xs:element name="annotations">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="notes" type="stringWithLang"/>
				<xs:element ref="cycle"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="cycle">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="stringWithLang" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="annot"   minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="annot">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="header"/>
				<xs:element ref="spec" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="header">
		<xs:complexType mixed="false">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="course"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="course">
		<xs:complexType>
			<xs:attribute name="id" use="required" type="courseId"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="stringWithLang" mixed="true">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element ref="spec"/>
		</xs:sequence>
		<xs:attribute ref="xml:lang"/>
	</xs:complexType>
	<xs:element name="spec">
		<xs:complexType>
			<xs:attribute name="code" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="courseId">
		<xs:restriction base="xs:string">
			<xs:pattern value="/[a-z]+[_[a-z]]+/"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== Sandy4321/statmod.ru/_annot/mm_an.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE staff SYSTEM "/htmlentities.dtd">
<annotations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://statmod.ru/annotations" xsi:schemaLocation="http://statmod.ru/annotations annot.xsd" spec="mm">
	<notes>
Структура образования на специализации Математическое Моделирование (кафедра статистического моделирования, отделение Прикладной математики и информатики мат-меха).	
	
Студенты обучаются на специализации с 3-го по 4-й курсы на бакалавриате и потом два года в магистратуре. 
На 3-м и 4-м курсах занятия очень плотные, свободных дней практически нет.

	<p>С 2013/2014 уч. года кафедра работает по профилю "Вычислительная стохастика и статистические модели" на бакалариате (магистратура в ближайших планах). Поэтому наступает переходный период.
Перечислим курсы бакалариата пока отдельно, в дальнейшем они будут структурированы.</p>

	</notes>
	<cycle>
	<name>Бакалавриант 3 курс</name>
		<annot>
			<header>
			 <course id="ball_teorver_kurs"/>
      <course id="ball_teorver_pract"/>
			</header>
Годовой курс &laquo;Теория вероятностей&raquo; (3 курс, 5 и 6 семестры) для всего отделения читается кафедрой Теории Вероятностей и Математической Статистики. Общекафедральные практические занятия в нашей группе ведет наша же кафедра (в отличие от других кафедр отделения), что обеспечивает достаточно пристойное освоение студентами понятийных и технических аспектов этой науки. Курс теории вероятностей поддерживается, кроме того, курсовой работой по этому предмету. 
		</annot>
			<annot>
			<header>
				<course id="ball_simul_discr"/>
			</header>
 Дискретное моделирование, 5 семестр
		</annot>
				<annot>
			<header>
				<course id="ball_simul"/>
			</header>
 Моделирование распределений, 6 семестр
		</annot>
			<annot>
			<header>
				<course id="ball_tex"/>
			</header>
 Вычислительный практикум, 5 семестр. Тех, слайды.
		</annot>
		<annot>
			<header>
				<course id="bmm_simul_pract"/>
			</header>
 Вычислительный практикум, 6 семестр. Практика по моделированию распределений.
		</annot>
		<annot>
			<header>
				<course id="bmm_automaton_base"/>
			</header>
Основы теории автоматных моделей, 5 семестр.
		</annot>
		<annot>
			<header>
				<course id="bmm_prog_c_lang"/>
				<course id="bmm_prog_c_pract"/>
			</header>
Спецвычпрактикум и Теория и практика программирования (5 семестр).  
		</annot>
		<annot>
			<header>
				<course id="bmm_prog_cpp_lang"/>	
				<course id="bmm_prog_cpp_pract"/>
			</header>
Прикладное программирование  и спецвычпрактикум (6 семестр). 
		</annot>
</cycle>

	<cycle>
	<name>Бакалавриант 4 курс</name>
		<annot>
			<header>
				<course id="bmm_fuzzy_sets"/>
     </header>
Курс посвящен развивающейся в данный момент области математики, известной как &laquo;нечеткая логика&raquo; (fuzzy logic). В курсе также рассматриваются различные методы принятия решений.
</annot>
		<annot>
			<header>
				<course id="bmm_petri_nets"/>
			</header>
Спецкурс дает обширные знания о сетях Петри, а также о дискретных процессах различных видов. Сети Петри будут особенно полезны тем, кто интересуется многопоточным программированием, так как они позволяют построить наглядную модель механизма семафоров для любого случая использования потоков.
		</annot>
	<annot>
			<header>
				<course id="bmm_idemp_algebra"/>
			</header>
Курс посвящен методам моделирования в идемпотентной алгебре, исследованию идемпотентной алгебры с операциями особого вида, а также решению линейных уравнений в идемпотентной алгебре.
		</annot>
		<annot>
			<header>
				<course id="bmm_appl_stat"/>
			</header>
			Начальный курс прикладной статистики, включающий анализ одномерных и двумерных данных 
			</annot>
		<annot>
			<header>
				<course id="bmm_stat_pract"/>
			</header>
			Обработка реальных данных с помощью компьютера. Пакет STATISTICA.
			</annot>
		<annot>
			<header>
				<course id="bmm_automaton_struct"/>
			</header>
Спецкурс продолжает курс &laquo;Основы теории автоматных моделей&raquo;, упор делается на алгебру логики, на различные способы задания и построения логических функций и на их анализ.
		</annot>
		<annot>
			<header>
				<course id="bmm_prog_cpp_advanced"/>
				<course id="bmm_prog_cpp_pract"/>
			</header>
Происходит дальнейшее изучение C++. Курс включает в себя написание клиент серверного приложения, моделирующего систему массового обслуживания. Клиентская часть программы реализована на языке С#, серверная часть на С++.  Данные от сервера к клиентскому приложению передаются с помощью Socket. Моделирование на сервере осуществляется в помощью симуляционных потоков и использует элементы передачи управления. Их использование позволяет приблизить моделирование к реальным процессам, происходящим в система массового обслуживания. Особое внимание уделяется таким возможностям языка C#, как интеграции с другими приложениями (MS Graph, Excel). Так как материал сложный, то можно сказать, что результатом является знакомство студентов с описанными выше понятиями и выполнение задания &laquo;по образцу&raquo;.
		</annot>
	<annot>
			<header>
				<course id="ball_communication"/>
			</header>
В курсе собраны технологии оформления и презентации научных исследований. 
		</annot>
		<annot>
				<header>
				<course id="ball_statprogR"/>
			</header>
Курс посвящен обучению студентов программированию статистических задач на языке R, специально предназначенном для этого.
 Задания, на основе которых происходит обучение, используют новый современный вероятностный и статистический материал, не включенный в другие курсы. 
		</annot>
		<annot>
				<header>
				<course id="bmm_prediploma"/>
			</header>
На занятиях происходят доклады по темам выпускных работ, как подробные на всю пару, так и репетиции защит выпускных работ.
		</annot>
		<annot>
			<header>
				<course id="ball_parallel_comp"/>
			</header>
Курс посвящен изучению методов решения различных задач при помощи параллельных алгоритмов. В качестве примера используются задачи математической физики. Также в курсе рассматривается устойчивость некоторых алгоритмов, опирающихся на метод Монте-Карло. 
		</annot>
		<annot>
			<header>
				<course id="ball_exper_design"/>
			</header>
Курс в статистическом цикле стоит особняком в связи с тем, что посвящен специальному разделу статистики &ndash; планированию эксперимента. 
		</annot>
  <annot>
			<header>
				<course id="ball_stat"/>
			</header>
Это базовый курс математической статистики, читаемый всему отделению. Он поддерживается практическими занятиями, имеющими специальную программу для студентов кафедры. 
  </annot>
	
</cycle>


	<cycle>
		<name>Вероятностный цикл</name>
		<annot>
			<header>
				<course id="all_teorver_pract"/>
				<course id="all_teorver_kurs"/>
			</header>
Годовой курс &laquo;Теория вероятностей&raquo; (3 курс, 5 и 6 семестры) для всего отделения читается кафедрой Теории Вероятностей и Математической Статистики. Общекафедральные практические занятия в нашей группе ведет наша же кафедра (в отличие от других кафедр отделения), что обеспечивает достаточно пристойное освоение студентами понятийных и технических аспектов этой науки. Курс теории вероятностей поддерживается, кроме того, курсовой работой по этому предмету. 
		</annot>
		<annot>
			<header>
				<course id="mm_statmod"/>
			</header>
 Курс включает в себя моделирование случайных величин, методы Монте-Карло. Частично поддерживается спец. выч. практикумом в 6 семестре.
		</annot>
		<annot>
			<header>
				<course id="all_statmod"/>
			</header>
В целом программа этой половины курса аналогична программе специального курса &laquo;Методы статистического моделирования&raquo;. Разница состоит в том, что в этом курсе изложение в меньшей степени использует продвинутые вероятностные понятия (так как студенты остальных  кафедр хуже наших ориентируются в вероятности). Поэтому и нашим студентам этот курс оказывается полезным (особенно не очень сильным). Курс поддерживается практическими занятиями. 
		</annot>
		<annot>
			<header>
				<course id="all_finmodel"/>
			</header>
 Программа курса включает в себя теорию арбитража в стохастических финансовых моделях, а также теорию расчетов для них.
		</annot>
		<annot>
			<header>
				<course id="all_finance_insurance"/>
			</header>
Курс посвящен моделям и процессам актуарной (страховой) математики.
		</annot>
	</cycle>
	<cycle>
		<name>Цикл &laquo;Дискретные системы&raquo;</name>
		<annot>
			<header>
				<course id="mm_automaton_base"/>
			</header>
Курс посвящен одной из главных тем специализации. В нем рассматриваются детерминированные автоматы, языки и связь между ними. На самом деле, этот курс дает начальные теоретические знания о построении компиляторов.
		</annot>
		<annot>
			<header>
				<course id="mm_fuzzy_sets"/>
			</header>
Курс посвящен развивающейся в данный момент области математики, известной как &laquo;нечеткая логика&raquo; (fuzzy logic). В курсе также рассматриваются различные методы принятия решений.
		</annot>
		<annot>
			<header>
				<course id="mm_automaton_struct"/>
			</header>
Спецкурс продолжает курс &laquo;Основы теории автоматных моделей&raquo;, упор делается на алгебру логики, на различные способы задания и построения логических функций и на их анализ.
		</annot>
		<annot>
			<header>
				<course id="mm_reliab_automaton"/>
			</header>
Спецкурс в некотором роде также продолжает &laquo;Основы теории автоматных моделей&raquo;, на этом курсе рассматриваются практические вопросы надежной (безотказной) работы автоматных моделей.
		</annot>
		<annot>
			<header>
				<course id="mm_petri_nets"/>
			</header>
Спецкурс дает обширные знания о сетях Петри, а также о дискретных процессах различных видов. Сети Петри будут особенно полезны тем, кто интересуется многопоточным программированием, так как они позволяют построить наглядную модель механизма семафоров для любого случая использования потоков.
		</annot>
